
package ru.itsc.backend.template;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TemplateService", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TemplateService {


    /**
     * 
     * @param id
     * @param rows
     * @return
     *     returns java.util.List<ru.gazprom_neft.metamap.entities.beans.Template>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemplatesByLimit", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.GetTemplatesByLimit")
    @ResponseWrapper(localName = "getTemplatesByLimitResponse", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.GetTemplatesByLimitResponse")
    public List<Template> getTemplatesByLimit(
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "rows", targetNamespace = "")
        int rows);

    /**
     * 
     * @param template
     * @param description
     */
    @WebMethod
    @RequestWrapper(localName = "addTemplate", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.AddTemplate")
    @ResponseWrapper(localName = "addTemplateResponse", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.AddTemplateResponse")
    public void addTemplate(
        @WebParam(name = "template", targetNamespace = "")
        String template,
        @WebParam(name = "description", targetNamespace = "")
        String description);

    /**
     * 
     * @param id
     * @return
     *     returns ru.gazprom_neft.metamap.entities.beans.Template
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.GetTemplate")
    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.GetTemplateResponse")
    public Template getTemplate(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @return
     *     returns ru.gazprom_neft.metamap.entities.beans.Template
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastTemplate", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.GetLastTemplate")
    @ResponseWrapper(localName = "getLastTemplateResponse", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", className = "ru.gazprom_neft.metamap.entities.beans.GetLastTemplateResponse")
    public Template getLastTemplate();

}
