
package ru.itsc.backend.template;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TemplateService", targetNamespace = "http://gazprom_neft.ru/metamap/entities/beans/", wsdlLocation = "http://sapdp7.gazprom-neft.local:50000/TemplateService/TemplateBean?wsdl")
public class TemplateService_Service
    extends Service
{

    private final static URL TEMPLATESERVICE_WSDL_LOCATION;
    private final static WebServiceException TEMPLATESERVICE_EXCEPTION;
    private final static QName TEMPLATESERVICE_QNAME = new QName("http://gazprom_neft.ru/metamap/entities/beans/", "TemplateService");
    private final static String URL_QUERY_PART = "/TemplateService/TemplateBean?wsdl";
    
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sapdp7.gazprom-neft.local:50000/TemplateService/TemplateBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEMPLATESERVICE_WSDL_LOCATION = url;
        TEMPLATESERVICE_EXCEPTION = e;
    }

    public TemplateService_Service(String hostUrl) throws MalformedURLException {
        super(new URL(hostUrl + URL_QUERY_PART), TEMPLATESERVICE_QNAME);
    }
    
    public TemplateService_Service() {
        super(__getWsdlLocation(), TEMPLATESERVICE_QNAME);
    }

    public TemplateService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEMPLATESERVICE_QNAME, features);
    }

    public TemplateService_Service(URL wsdlLocation) {
        super(wsdlLocation, TEMPLATESERVICE_QNAME);
    }

    public TemplateService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEMPLATESERVICE_QNAME, features);
    }

    public TemplateService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TemplateService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TemplateService
     */
    @WebEndpoint(name = "TemplateBeanPort")
    public TemplateService getTemplateBeanPort() {
        return super.getPort(new QName("http://gazprom_neft.ru/metamap/entities/beans/", "TemplateBeanPort"), TemplateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TemplateService
     */
    @WebEndpoint(name = "TemplateBeanPort")
    public TemplateService getTemplateBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gazprom_neft.ru/metamap/entities/beans/", "TemplateBeanPort"), TemplateService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEMPLATESERVICE_EXCEPTION!= null) {
            throw TEMPLATESERVICE_EXCEPTION;
        }
        return TEMPLATESERVICE_WSDL_LOCATION;
    }

}
