
package ru.itsc.backend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MetamapBeanRemote", targetNamespace = "http://gazprom_neft.ru/metamap/bean/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetamapBeanRemote {


    /**
     * 
     * @param id
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveGraphMlPi", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.RetrieveGraphMlPi")
    @ResponseWrapper(localName = "retrieveGraphMlPiResponse", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.RetrieveGraphMlPiResponse")
    public String retrieveGraphMlPi(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveGraphMl", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.RetrieveGraphMl")
    @ResponseWrapper(localName = "retrieveGraphMlResponse", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.RetrieveGraphMlResponse")
    public String retrieveGraphMl(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
