
package ru.itsc.backend.planedmap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlanedMetamapService", targetNamespace = "http://gazprom_neft.ru/metamap/bean/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlanedMetamapService {


    /**
     * 
     * @return
     *     returns ru.gazprom_neft.metamap.bean.PlanedMetamap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastPlanedMetamap", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetLastPlanedMetamap")
    @ResponseWrapper(localName = "getLastPlanedMetamapResponse", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetLastPlanedMetamapResponse")
    public PlanedMetamap getLastPlanedMetamap();

    /**
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.util.List<ru.gazprom_neft.metamap.bean.PlanedMetamap>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlanedMetamaps", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetPlanedMetamaps")
    @ResponseWrapper(localName = "getPlanedMetamapsResponse", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetPlanedMetamapsResponse")
    public List<PlanedMetamap> getPlanedMetamaps(
        @WebParam(name = "startDate", targetNamespace = "")
        Date startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        Date endDate);

    /**
     * 
     * @param id
     * @param rows
     * @return
     *     returns java.util.List<ru.gazprom_neft.metamap.bean.PlanedMetamap>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlanedMetamapsByLimit", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetPlanedMetamapsByLimit")
    @ResponseWrapper(localName = "getPlanedMetamapsByLimitResponse", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetPlanedMetamapsByLimitResponse")
    public List<PlanedMetamap> getPlanedMetamapsByLimit(
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "rows", targetNamespace = "")
        int rows);

    /**
     * 
     * @param id
     * @return
     *     returns ru.gazprom_neft.metamap.bean.PlanedMetamap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlanedMetamap", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetPlanedMetamap")
    @ResponseWrapper(localName = "getPlanedMetamapResponse", targetNamespace = "http://gazprom_neft.ru/metamap/bean/", className = "ru.gazprom_neft.metamap.bean.GetPlanedMetamapResponse")
    public PlanedMetamap getPlanedMetamap(
        @WebParam(name = "id", targetNamespace = "")
        long id);

}
